export const bioParagraphs = [
  "Reflecting on my life over time, during the different stages of life, I realized that I spent so much of my life trying to be enough for everyone else that somewhere along the way, I forgot to ask myself if I was enough for me. Like so many of us, I allowed other people’s opinions, unrealistic expectations, and society’s idea of what beauty should look like to become louder than my own voice. For years, I thought I needed a different life… but what I really needed was a different conversation with myself. When I began changing the way I spoke to myself… with more love, more grace, and a little more compassion… so many other things began to change too.",
  "That’s why I share my journey so openly through social media, community events, creativity, modelling, acting, hosting, and my two editions of a self-love colouring book. Not because I have it all figured out… because I definitely don’t. I share because I know what it feels like to question yourself… to compare yourself… and to wonder if you’re enough. So many of us have felt that way at some point. If something I share helps another woman love herself a little more, believe in herself a little more, or simply see herself through kinder eyes… then every conversation is worth having.",
  "Somewhere along the way, all of this grew into Take Up Space On Purpose. It wasn’t something I sat down and carefully planned… it grew naturally from my own journey and from the conversations I was already having with other women. Now, we’re building a community where self-love becomes the strength we share. This is a community where we can talk honestly about our bodies… the parts we love, the parts we’re still learning to love, and all the ways our bodies change as we move through life. Over here we’re embracing body positivity, growing older, and loving who we are at every age… because aging doesn’t make any of us less beautiful, less valuable, or less deserving of being seen.",
  "We celebrate one another, encourage one another, and genuinely want to see each other win. We show up as we are… support one another without judgment… and remember that another woman’s light never takes anything away from our own. Everything I create… whether it’s a conversation, a piece of content, a community event, a creative project, or something new I’m quietly bringing to life… comes from that same place. I want us to change the conversations we have with ourselves. When we begin speaking to ourselves differently… we begin seeing ourselves differently. When one of us women starts seeing ourselves through kinder eyes… we often help another woman do the same.",
];

export const mantraIntro =
  "This is where we take a deep breath… and say it together, out loud.";

export const mantra =
  "I am enough. I choose me. I love the woman I am… and I will Take Up Space On Purpose.";
